packages:
  - packages/*
overrides:
  sass-embedded: 1.100.0

allowBuilds:
  '@parcel/watcher': true
  core-js: set this to true or false
  electron: set this to true or false
  esbuild: true
  highlight.js: set this to true or false
minimumReleaseAge: 0
trustLockfile: true
