export const view = (state) => state.view
export const locale = (state) => state.locale
export const roundedBorders = (state) => state.roundedBorders
export const barColor = (state) => state.barColor
export const color = (state) => state.color
export const backgroundColor = (state) => state.backgroundColor
export const innerColor = (state) => state.innerColor
export const innerBackgroundColor = (state) => state.innerBackgroundColor
export const noHeader = (state) => state.noHeader
export const noFooter = (state) => state.noFooter
export const disable = (state) => state.disable
export const noBorder = (state) => state.noBorder
export const noShadow = (state) => state.noShadow

export const selectedDate = (state) => state.selectedDate
export const shortDayLabel = (state) => state.shortDayLabel
export const shortMonthLabel = (state) => state.shortMonthLabel
export const showMonthLabel = (state) => state.showMonthLabel
export const shortYearLabel = (state) => state.shortYearLabel
export const showWeekdayLabel = (state) => state.showWeekdayLabel
export const noDays = (state) => state.noDays
export const noMonths = (state) => state.noMonths
export const noYears = (state) => state.noYears

export const selectedTime = (state) => state.selectedTime
export const hour24Format = (state) => state.hour24Format
export const showAmPmToggle = (state) => state.showAmPmToggle
export const noMinutes = (state) => state.noMinutes
export const noHours = (state) => state.noHours
