export default {
  view: 'time',
  locale: 'en-us',
  roundedBorders: true,
  borderColor: '#ccc',
  barColor: '#ccc',
  color: 'white',
  backgroundColor: 'primary',
  innerColor: 'white',
  innerBackgroundColor: 'primary',
  noHeader: false,
  noFooter: true,
  dense: false,
  disable: false,
  noBorder: false,
  noShadow: false,

  selectedDate: '2019-04-01',
  shortDayLabel: false,
  shortMonthLabel: false,
  showMonthLabel: false,
  shortYearLabel: false,
  showWeekdayLabel: false,
  noDays: false,
  noMonths: false,
  noYears: false,

  selectedTime: '11:05',
  hour24Format: true,
  noMinutes: false,
  noHours: false
}
